In [1]:
import numpy as np

In [2]:
popsize = 10; # size of the swarm
npar = 2; # number of dimensions
maxit = 100; # number of iterations
c1 = 1; # cognitive parameter
c2 = 4-c1; # social parameter
C=1; # constriction factor

In [33]:
par = np.random.rand(10,2)*10
vel = np.random.rand(10,2)*10

In [39]:
par

array([[7.87278758, 4.58900849],
       [0.85571063, 6.98062283],
       [2.51702399, 3.08540637],
       [4.18039711, 9.17326228],
       [1.73724755, 9.19505394],
       [3.5054405 , 3.24614383],
       [1.69907833, 0.95071194],
       [8.65732045, 3.90151198],
       [4.2212826 , 1.0320642 ],
       [7.27783372, 2.42830341]])

In [41]:
np.amin(par, axis=0)

array([0.85571063, 0.95071194])

In [26]:
function = lambda x: -1 * np.exp(0.2 * np.sqrt(((x) - 1)**2 + ((x) + 1)**2) + np.cos(x) + np.sin(x))

In [31]:
function = np.vectorize(function)

In [32]:
function(par)

array([[ -5.46434311,  -4.74238092],
       [ -1.07469685, -17.11713159],
       [ -0.77450698,  -0.79958562],
       [-30.23889935,  -3.20736513],
       [-14.30481412,  -9.1319381 ],
       [ -5.59403018,  -4.94648482],
       [ -2.84521049,  -2.72200542],
       [ -6.07974963, -20.09215833],
       [-29.76151042, -31.8567034 ],
       [ -7.20048673,  -5.48435051]])